# https://artifacthub.io/packages/helm/minio/minio
## minio mode, i.e. standalone or distributed
mode: standalone ## other supported values are "standalone"

# Number of MinIO containers running
replicas: 1

## Enable persistence using Persistent Volume Claims
## ref: http://kubernetes.io/docs/user-guide/persistent-volumes/
##
persistence:
 %{~ if trimspace(minio_persistence_size) != "" }
  enabled: true
  size: ${minio_persistence_size}
%{ else }
  enabled: false
%{~ endif ~}
%{~ if trimspace(minio_persistence_storage_class_name) != "" }
  storageClass: ${minio_persistence_storage_class_name}
%{~ endif ~}
## Node labels for pod assignment
## Ref: https://kubernetes.io/docs/user-guide/node-selection/
##
%{~ if trimspace(minio_node_affinity) != "" }
affinity:
  ${minio_node_affinity}
%{~ endif ~}

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
##
resources:
  requests:
    cpu: 250m
    memory: 512Mi

## Set default accesskey, secretkey, Minio config file path, volume mount path and
## number of nodes (only used for Minio distributed mode)
## AccessKey and secretKey is generated when not set
## Distributed Minio ref: https://docs.minio.io/docs/distributed-minio-quickstart-guide
##
accessKey: ${minio_access_key}
secretKey: ${minio_secret_key}

## Specify the service account to use for the MinIO pods. If 'create' is set to 'false'
## and 'name' is left unspecified, the account 'default' will be used.
serviceAccount:
  create: true

defaultBucket:
  enabled: true
  ## If enabled, must be a string with length > 0
  name: ${bucket_name}
